version: '3'
services:
  login-service:
    build:
      context: login-service
      dockerfile: Dockerfile
    image: configservice:1.0
    ports:
      - "8888:8888"

  user-service: 
    build:
      context: user-service
      dockerfile: Dockerfile
    image: user-service:1.0
    ports:
      - "9999:9999"
    restart: on-failure
